apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: default
  annotations:
    deployment-slot: "blue"
spec:
  selector:
    app: demo-app
    slot: blue
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30090